routes/web.php
Route::get('reset','Frontend\UserController@reset')->name('reset');
Route::post('reset-password','Frontend\UserController@changePassword')->name('reset-password');


/********************  api ****************************************/

Route::prefix('api/')->group(function () {
    Route::get('categories','Admin\CategoryController@apiCategories');
    Route::post('categories/attributes','Admin\CategoryController@apiAttributes');

    /********************   category search route ****************************************/

    Route::get('search/{sku}/{value}','Frontend\ProductController@productAllProducts');
    Route::get('sort-desc-products/{sku}/{value}','Frontend\ProductController@GetDescProducts');
    Route::get('sort-asc-products/{sku}/{value}','Frontend\ProductController@GetAscProducts');
    Route::get('sort-visit-products/{sku}/{value}','Frontend\ProductController@GetVisitedProducts');
    Route::get('sort-sell-products/{sku}/{value}','Frontend\ProductController@GetSellProducts');
    Route::get('sort-new-products/{sku}','Frontend\ProductController@GetNewProducts');


    /********************   sells products ****************************************/

    Route::get('get/sell-products/{value}','Frontend\ProductController@productSellData');
    Route::get('sort-sells-new-products/{value}','Frontend\ProductController@GetSellsNewProducts');
    Route::get('sort-sells-visited-products/{value}','Frontend\ProductController@GetSellsVisitedProducts');
    Route::get('sort-sells-ace-price-products/{value}','Frontend\ProductController@GetSellsAcePriceProducts');
    Route::get('sort-sells-desc-price-products/{value}','Frontend\ProductController@GetSellsDescPriceProducts');

    /********************   main  sort  new products route ****************************************/

    Route::get('get/new-products/{value}','Frontend\ProductController@productNewData');
    Route::get('sort-sell-product/{value}','Frontend\ProductController@GetNewSellProducts');
    Route::get('sort-visit-products/{value}','Frontend\ProductController@GetNewsVisitedProducts');
    Route::get('sort-ace-products/{value}','Frontend\ProductController@GetNewsAceProducts');
    Route::get('sort-desc-products/{value}','Frontend\ProductController@GetNewsDeceProducts');

    /********************  main search sort route  ****************************************/

    Route::get('search-all/{data}/{value}','Frontend\ProductController@searchAll');
    Route::get('search-price-desc/{data}/{value}','Frontend\ProductController@searchPriceDesc');
    Route::get('search-price-asc/{data}/{value}','Frontend\ProductController@searchPriceAsc');
    Route::get('search-visit/{data}/{value}','Frontend\ProductController@searchVisit');
    Route::get('search-sells/{data}/{value}','Frontend\ProductController@searchSells');

});



/********************  admin panel ****************************************/

Route::group(['middleware' => ['admin']], function () {
    Route::prefix('admin/')->group(function (){
        Route::get('dashboard', 'Admin\AdminController@index')->name('dashboard');
        Route::resource('categories', 'Admin\CategoryController');
        Route::resource('texts', 'Admin\TextController');
        Route::resource('costs', 'Admin\CostController');
        Route::resource('users', 'Admin\AdminUserController');
        Route::get('categories/{slug}/setting', 'Admin\CategoryController@indexSetting')->name('categories.indexSetting');
        Route::post('categories/{slug}/setting', 'Admin\CategoryController@saveSetting');
        Route::post('photos/create','Admin\PhotoController@store')->name('photos.store');
//        Route::post('photos/destroy/{id}','Admin\PhotoController@destroy')->name('photos.delete');

        Route::resource('attributes', 'Admin\AttributeGroupController');
        Route::resource('attributes-value', 'Admin\AttributeValueController');
        Route::get('attribute-group-name/{id}','Admin\AttributeValueController@getAttGroup')->name('attribute.group.name');
        Route::resource('brands', 'Admin\BrandController');
        Route::resource('metas', 'Admin\MetaController');
        Route::resource('products', 'Admin\ProductController');
        Route::get('product-attributes', 'Admin\AttributeValueController@productValues')->name('product.attribute');
        Route::resource('coupons', 'Admin\CouponController');
        Route::get('photos', 'Admin\PhotoController@upload');
        Route::post('photos/upload', 'Admin\PhotoController@upload')->name('photos.upload');
        Route::resource('comments','Admin\CommentController');
        Route::patch('comments/read/{id}','Admin\CommentController@read');
        Route::resource('orders','Admin\OrderController');
        Route::post('orders/markAsRead','Admin\OrderController@markAsRead')->name('orders.markAsRead');
        Route::resource('galleries','Admin\GalleryController');
        Route::patch('update/slider/{id}', 'Admin\GalleryController@update_photo')->name('slider.update');

        Route::delete('photos/{id}','Admin\PhotoController@destroy');
        Route::get('discounts' , 'Admin\DiscountController@index')->name('group.discount');
        Route::post('discounts/categories' , 'Admin\DiscountController@storeCategories')->name('discounts.categories');
        Route::post('increase/categories' , 'Admin\DiscountController@storeIncreaseCategories')->name('increase.categories');
        Route::post('discounts/products' , 'Admin\DiscountController@storeProducts')->name('discounts.products');
        Route::resource('socials','Admin\SocialController');

        // products api
        Route::get('all-products', 'Admin\ProductController@getProducts');
        Route::post('search/products/{value}' , 'Admin\ProductController@search_products');

        //attribute group api
        Route::get('all-att-group', 'Admin\AttributeGroupController@getAttGroups');
        Route::post('search/attribute-group/{value}' , 'Admin\AttributeGroupController@search_attGroup');

        //attribute value api
        Route::get('all-att-value', 'Admin\AttributeValueController@getAttValuess');
        Route::post('search/attribute-value/{value}' , 'Admin\AttributeValueController@search_attValue');


    });
});


/********************  user panel ****************************************/

Route::group(['middleware'=>'auth'], function() {
   // Route::get('/profile', 'Frontend\UserController@profile')->name('user.profile');
    Route::get('/profile','Frontend\ProfileController@profile')->name('profile');
    Route::get('/profile/additional-info','Frontend\ProfileController@profileAdditional')->name('additional-info');
    Route::post('/profile/additional-info','Frontend\ProfileController@updateProfile')->name('additional.info');
    Route::get('/profile/personal-info','Frontend\ProfileController@profilePersonal')->name('personal-info');
    Route::resource('/profile/addresses','Frontend\AddressController');
    Route::post('/profile/addresses/enable/{id}' , 'Frontend\AddressController@enable');
    Route::get('/profile/favorites','Frontend\ProfileController@favorites')->name('favorites');
    Route::get('/profile/orders','Frontend\ProfileController@orderList')->name('orders.list');
    Route::get('/cart','Frontend\CartController@showCart')->name('cart.show');
    Route::get('/order-verify/{value?}', 'Frontend\OrderController@verify')->name('order.verify');
    Route::get('/payment-verify', 'Frontend\PaymentController@verify')->name('payment.verify');
    Route::get('/shopping', 'Frontend\ShoppingController@index')->name('shopping');
    Route::get('/shopping-payment', 'Frontend\ShoppingController@shoppingPayment')->name('shopping.payment');
    Route::get('/shopping-complete-buy','Frontend\ShoppingController@completeBuy')->name('shopping.complete');
    Route::get('/shopping-not-complete-buy','Frontend\ShoppingController@notCompleteBuy')->name('shopping.notComplete');
    Route::post('/coupon','Admin\CouponController@addCoupons')->name('add.coupon');
    Route::get('product/comment/{product:sku}/{slug}','Admin\CommentController@show')->name('comment.show');
    Route::post('product/comment/{sku}','Admin\CommentController@create')->name('comment.create');
    Route::post('/product/recommend/{id}','Admin\CommentController@recommend')->name('comment.recommend');

    //add product to favorite list
    Route::get('favorite','Frontend\FavoriteController@add')->name('favorite.add');
    Route::post('favorite-add/{sku}','Frontend\FavoriteController@add');
});


/********************  guest page  ****************************************/

Route::get('/','Frontend\MainController@index')->name('/');
Route::get('add/{id}/{idd?}','Frontend\CartController@addToCart')->name('add');
Route::post('remove/{id}','Frontend\CartController@removeCart')->name('cart.remove');
Route::get('/product/{sku}/{slug}','Frontend\ProductController@index')->name('product');
//all cat products possessing
Route::get('/search/{sku}/{slug}','Frontend\ProductController@productList')->name('get.productList');
Route::get('/search/sells','Frontend\ProductController@productSell')->name('get.productSell');
Route::get('/search/news','Frontend\ProductController@productNew')->name('get.productNew');
Route::get('/search','Frontend\ProductController@search')->name('search');

Route::get('/privacy','HomeController@privacy')->name('privacy');
Route::get('/about-us','HomeController@about')->name('about');
Route::get('/careers','HomeController@careers')->name('careers');
Route::get('/contact','HomeController@contact')->name('contact');
Route::get('/terms-of-use','HomeController@teams')->name('teams');
Route::get('/questions','HomeController@question')->name('questions');
Route::get('/returning-product','HomeController@returning')->name('returning');
Route::get('/register-product','HomeController@register')->name('register.product');
Route::get('/send-product','HomeController@send')->name('send.product');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{


    public function commentable()
    {
        return $this->morphTo();
    }
    public function user()
    {
        return $this->belongsTo(User::class,'written_by','id');
    }
    public function users()
    {
        return $this->belongsTo(User::class,'accepted_by','id');
    }

}

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $uploads = '/storage/';

    public function getPathAttribute($photo)
    {
        return $this->uploads . $photo;
    }
    public function brands()
    {
       return $this->belongsToMany(Brand::class);
    }

    public function products()
    {
       return $this->belongsToMany(Product::class);
    }
}

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Order;
use App\OrderItem;
use App\Product;
use App\Repository\Eloquent\CommentRepository;
use Illuminate\Http\Request;

class CommentController extends Controller
{

    protected $comments;

    public function __construct(CommentRepository $comments)
    {
        $this->comments = $comments;
    }

    public function index()
    {
        $comments = $this->comments->allWithPaginate(10);
        return view('admin.comments.index', compact(['comments']));
    }
    public function read($id)
    {
        $comment= $this->comments->findById($id);
        $comment->read = 1;
         $comment->save();
    }

    public function create(Request $request,$sku)
    {
        $this->comments->create($request,$sku);
        return back();
    }


    public function store(Request $request)
    {
        //
    }

    public function show(Product $product)
    {
        $order =Order::with('items')->where('user_id',auth()->id())->whereHas('items',function ($q)use($product){
            return $q->where('product_id',$product->id);
        })->get();
        if (count($order)!= 0){
            return view('product.comment', compact(['product']));
        }
        alert('خطا', 'برای ثبت نظر، قبلا باید کالا خریداری شده باشد','error');
        return back();

    }


    public function edit($id)
    {
        $comment= $this->comments->findById($id);
        if ($comment->status == 0){
            toast('با موفقیت منتشر  شد', 'success');
            $comment->status =1;
        }
        else{
            toast('تایید نشد', 'success');
            $comment->status =0;
        }
        $comment->accepted_by=auth()->id();
        $comment->save();
        return back();
    }


    public function update(Request $request, $id)
    {
       return $request;
    }

    public function destroy($id)
    {
        $comment = $this->comments->findById($id);
        $comment->delete();
    }
    public function recommend(Request $request,$id)
    {
        $comment = $this->comments->findById($id);
        if ($request->recommend == 'yes')
            $comment->recommend ++;
        else if ($request->recommend == 'no')
            $comment->notrecommend ++;
        $comment->save();
        toast('نظر شما با موفقیت ثبت شد', 'success');
        return back();
    }
}

resources/views/admin/comments/create.blade.php
@extends('admin.layouts.master')

@section('style')
    <link rel="stylesheet" href="{{asset('/admin/dist/css/dropzone.css')}}">
@endsection
@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">داشبورد</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-left">
                            <li class="breadcrumb-item"><i class="blue">برند</i></li>
                            <li class="breadcrumb-item active">داشبورد</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title pull-right">ایجاد برند جدید</h3>
                </div>

                <!-- /.card-header -->

                <div class="card-body">
                    @if($errors->any())
                        <ol  style=" list-style-type: persian" >
                            <div class="  alert alert-danger mr-1">
                                @foreach($errors->all() as $error)
                                    <li >{{$error}}</li>
                                @endforeach
                            </div>
                        </ol>
                    @endif
                    <form id="myForm" method="post" action="/admin/brands">
                        @csrf
                        <div class="card-body offset-md-2 col-md-8">
                            <div class="form-group">
                                <label>نام برند</label>
                                <input name="title" type="text" class="form-control" placeholder="نام ویژگی را وارد کنید ...">
                            </div>
                            <div class="form-group">
                                <label>توضیحات</label>
                                <textarea id="textareaDescription" type="text" name="description" class="ckeditor form-control" placeholder="توضیحات محصول را وارد کنید..."></textarea>
                            </div>
                            <div class="form-group">
                                <label for="photo">گالری تصاویر</label>
                                <input type="hidden" name="photo_id[]" id="brand-photo">
                                <div id="photo" class="dropzone"></div>
                            </div>

                            <button type="submit" onclick="productGallery()" class="btn btn-success pull-left ">ذخیره</button>
                        </div>

                    </form>
                </div>

            </div>
            <!-- /.card-body -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('script')
    <script type="text/javascript" src="{{asset('/admin/dist/js/dropzone.js')}}"></script>
    <script type="text/javascript" src="{{asset('/admin/plugins/ckeditor/ckeditor.js')}}"></script>

    <script>
        Dropzone.autoDiscover = false;
        var photosGallery = []
        var drop = new Dropzone('#photo', {
            addRemoveLinks: true,
            acceptedFiles: ".jpg ,.png",
            maxFiles: 3,
            maxFilesize: 0.3,
            paramName: "file",
            acceptedMimeTypes: null,
            acceptParameter: null,
            enqueueForUpload: true,
            dictDefaultMessage:"افزودن عکس برند",
            dictFileTooBig:"اندازه عکس بزرگ است",// image size error message
            dictInvalidFileType:"فرمت فایل اشتباه است",// file type error message
            dictCancelUpload:"لغو آپلود",//cancel error message
            dictCancelUploadConfirmation:"آیا می خواهید آپلود را متوقف کنید؟", //cancel conform
            dictMaxFilesExceeded:"برای هر برند فقط 3 عکس می توانید آپلود کنید",
            dictRemoveFile:"حذف",// remove file

            url: "{{ route('photos.upload') }}",
            sending: function(file, xhr, formData){
                formData.append("_token","{{csrf_token()}}")
            },
            success: function(file, response){
                photosGallery.push(response.photo_id)
            }
        });
        productGallery = function(){
            document.getElementById('brand-photo').value = photosGallery
        }
        CKEDITOR.replace('textareaDescription',{
            customConfig: 'config.js',
            toolbar: 'simple',
            language: 'fa',
            removePlugins: 'cloudservices, easyimage'
        });

    </script>


@endsection

resources/views/admin/comments/edit.blade.php
@extends('admin.layouts.master')

@section('style')
    <link rel="stylesheet" href="{{asset('/admin/dist/css/dropzone.css')}}">
@endsection
@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">داشبورد</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-left">
                            <li class="breadcrumb-item"><i class="blue">برند</i></li>
                            <li class="breadcrumb-item active">داشبورد</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title pull-right">ویرایش برند <span class="red">{{$brand->title}}</span></h3>
                </div>

                <!-- /.card-header -->

                <div class="card-body">
                    @if($errors->any())
                        <ol  style=" list-style-type: persian" >
                            <div class="  alert alert-danger mr-1">
                                @foreach($errors->all() as $error)
                                    <li >{{$error}}</li>
                                @endforeach
                            </div>
                        </ol>
                    @endif
                    <form  method="post" action="/admin/brands/{{$brand->slug}}">
                        @csrf
                        <input type="hidden" name="_method" value="PATCH">
                        <div class="card-body offset-md-2 col-md-8">
                            <div class="form-group">
                                <label>نام برند</label>
                                <input value="{{$brand->title}}" name="title" type="text" class="form-control" placeholder="نام ویژگی را وارد کنید ...">
                            </div>
                            <div class="form-group">
                                <label>توضیحات</label>
                                <textarea  id="textareaDescription" type="text" name="description" class="ckeditor form-control" placeholder="توضیحات محصول را وارد کنید...">{{$brand->description}}</textarea>
                            </div>
                            <div class="form-group">
                                <label for="photo">گالری تصاویر</label>
                                <input type="hidden" name="photo_id[]" id="brand-photo">
                                <div id="photo"  class="dropzone"></div>
                                <div class="row">
                                    @foreach($brand->photos as $photo)
                                        <div class="col-sm-3" id="updated_photo_{{$photo->id}}">
                                            <img width="100" height="100" src="{{$photo->path }}" >
                                            <button type="button" class="btn btn-danger" onclick="removeImages({{$photo->id}})" >حذف</button>
                                        </div>
                                    @endforeach
                                </div>
                            </div >
                            <button type="submit" onclick="brandGallery()" class="btn btn-success pull-left ">ذخیره</button>
                        </div>

                    </form>
                </div>

            </div>
            <!-- /.card-body -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('script')
    <script type="text/javascript" src="{{asset('/admin/dist/js/dropzone.js')}}"></script>
    <script type="text/javascript" src="{{asset('/admin/plugins/ckeditor/ckeditor.js')}}"></script>

    <script>
        Dropzone.autoDiscover = false;
        var photosGallery = []
        var photos = [].concat({{$brand->photos->pluck('id')}})
        var drop = new Dropzone('#photo', {
            addRemoveLinks: true,
            acceptedFiles: ".jpg ,.png",
            maxFiles: 3,
            maxFilesize: 0.3,
            paramName: "file",
            acceptedMimeTypes: null,
            acceptParameter: null,
            enqueueForUpload: true,
            dictDefaultMessage:"افزودن عکس برند",
            dictFileTooBig:"اندازه عکس بزرگ است",// image size error message
            dictInvalidFileType:"فرمت فایل اشتباه است",// file type error message
            dictCancelUpload:"لغو آپلود",//cancel error message
            dictCancelUploadConfirmation:"آیا می خواهید آپلود را متوقف کنید؟", //cancel conform
            dictMaxFilesExceeded:"بیشتر از 3 عکس نمی توانید",
            dictRemoveFile:"حذف",// remove file

            url: "{{ route('photos.upload') }}",
            sending: function(file, xhr, formData){
                formData.append("_token","{{csrf_token()}}")
            },
            success: function(file, response){
                photosGallery.push(response.photo_id)
            }
        });
        brandGallery = function(){
            document.getElementById('brand-photo').value = photosGallery.concat(photos)
        };
        CKEDITOR.replace('textareaDescription',{
            customConfig: 'config.js',
            toolbar: 'simple',
            language: 'fa',
            removePlugins: 'cloudservices, easyimage'
        });

        removeImages = function(id){
            console.log(photos.length)

            var index = photos.indexOf(id)
            photos.splice(index, 1);
            document.getElementById('updated_photo_' + id).remove();
        };
    </script>


@endsection